### PR TITLE
Merge v0.2 into master

### PR DESCRIPTION
**Pull request by bayandin**

### CODE REVIEW

**Comment by tk8817** [comment]
Hey @bayandin - V0.2 looks very interesting, any way to get a little bit more documentation on the suggested setup/config for remote workers?

**Comment by sleekweasel** [comment]
Remote workers for which target? :)

Our solution for web is just a Selenium grid

Android probably doesn't need remote stuff, unless you have more than 128 devices.

Our iOS system is cobbled together from what we used to do when we used Rajdeep's parallel_calabash project here on GitHub. I could publish that, but I'll have to warn you that it's not especially pretty - look at my fork's misc/setup_ios_host file for a hint.

**Comment by tk8817** [comment]
@sleekweasel - Looking for info the redis setup for the queueing and how that relates to kicking off work on a single machine or many machines.

```   
 -q ARRAY,`url,name` Url for TCP connection: `redis://[password]@[hostname]:[port]/[db]` (password, port and database are optional), for unix socket connection: `unix://[path to Redis socket]`. Default is redis://127.0.0.1:6379 and name is `queue`
```

**Comment by sleekweasel** [comment]
@tk8817 The workers all run on the central test machine, so redis only needs to run locally, and doesn't need to be shared: we actually start and stop it with the overall test run. If remote machines are involved, it's because the scripts that the workers run are copying files and ssh-ing to execute stuff on whichever user@machine each worker has been told to use. (Our rakefile puts that information into the environment argument, along with the device id for each worker.)

**Comment by tk8817** [comment]
Thanks @sleekweasel - exactly the info I was looking for!

**Pull request merged**
